import { prisma } from '../../prisma';
import type { StepInput } from '../types';

export async function directorPlanStep(input: StepInput): Promise<{ progress: number; message: string }> {
  const placeholderBible = {
    generated_at: new Date().toISOString(),
    continuity_rules: {
      ratio: 'locked-by-series',
      language: 'BM_SABAH primary',
      style: 'LOCAL_X_ANIME'
    },
    notes: 'placeholder director plan generated by worker'
  };

  await prisma.series.update({
    where: { id: input.seriesId },
    data: { seriesBible: placeholderBible }
  });

  return { progress: 100, message: 'director_plan updated series bible' };
}
